decoder:
  image_size: [180, 320]
  patch_size: 16
  latent_grid: [11, 20]
  resize_mode: bilinear
  latent_dim: 768
  embed_dim: 1024
  depth: 24
  num_heads: 16
  mlp_ratio: 4.0
  dropout: 0.0
  attention_dropout: 0.0
  qkv_bias: true

vision:
  repo_id: facebook/dinov3-vitb16-pretrain-lvd1689m

dataset:
  dataset_name: imagenet-1k
  dataset_config: null
  split: train
  image_key: image
  buffer_size: 2048
  min_scale: 0.75
  max_scale: 1.0
  random_flip: true
  seed: 0

dataloader:
  batch_size: 8
  num_workers: 0
  pin_memory: true

optimizer:
  lr: 1.0e-4
  betas: [0.5, 0.9]
  weight_decay: 0.0
  eps: 1.0e-8
  grad_clip: 1.0

scheduler:
  enabled: true
  warmup_steps: 2000
  total_steps: 200000
  min_lr: 2.0e-5

trainer:
  max_steps: 200000
  grad_accum_steps: 1
  precision: fp32
  seed: 1234
  device: null
  resume_checkpoint: null

logging:
  log_interval: 50
  checkpoint_interval: 5000
  output_dir: checkpoints/decoder
  run_name: decoder
  use_wandb: true
  wandb_project: world_model
  wandb_entity: null

losses:
  recon_weight: 1.0
  perceptual_weight: 1.0

ema:
  enabled: true
  decay: 0.9978
  device: null
