logging:
  project: world_model
  entity: null
  run_name: null
  log_interval: 1
  checkpoint_interval: 500
  output_dir: checkpoints
  tau_log_limit: 100

trainer:
  evaluation_interval: 500
  max_steps: null
  grad_accum_steps: 8
  precision: bf16
  seed: 3
  device: cuda
  resume_checkpoint: null
  single_batch_overfit: false
  lr_warmup_steps: 500
  lr_warmup_lr: 5.0e-6
  lr_final: null
  lr_final_step: null

evaluator:
  max_batches: 1
  video_sample_indices: [0] # the episode to log the video for
  rollout_start_frame: 6
  rollout_signal_level: 0.9
  clean_signal_level: 1.0
  precision: bf16

train_data:
  train_dataset:
    repo_id: aractingi/droid_1.0.1
    episodes: null # null means all episodes
    cameras:
      - observation.images.exterior_1_left
      - observation.images.exterior_2_left
      - observation.images.wrist_left
    action_keys:
      - observation.state
    action_representation: position # position or delta
    action_normalization: mean_std # min_max or mean_std
    action_normalization_params:
      mean: [0.01428347627459065, 0.23987777195473095, -0.014661363646208965, -2.027954954645529, -0.035476306435143545, 2.3233678805030076, 0.08326671319745274, 0.36085284714413735]
      std: [0.3244343844169754, 0.5158281965633522, 0.2901322476548548, 0.5021871776809874, 0.5331921797732538, 0.46856794632856424, 0.7446577730524244, 0.40315882970033534]
    sequence_length_distribution: # Dreamerv4 doesn't specify the proportion but I'll guess 0.8 short batches at the begginning and towards the end go to full long batches probably. For now let's keep small batches, will implement the evolution of this distribution later.
      "7": 0.8
      "11": 0.2
    frame_delta_seconds: 5.0 / 15.0
    independent_frames_probability: 0.3 # from Dreamerv4
    drop_action_probability: 0.75 # from Dreamerv4
    decoder_retry_attempts: 10

  train_dataloader:
    batch_size: 256 # global batch size
    shuffle: true
    num_workers: 0
    pin_memory: false

eval_data:
  eval_dataset:
    repo_id: aractingi/droid_1.0.1
    episodes: [0, 1, 2, 3]
    episode_midpoint_only: true
    cameras:
      - observation.images.exterior_1_left
    action_keys:
      - observation.state
    action_representation: position
    action_normalization: mean_std
    action_normalization_params:
      mean: [0.01428347627459065, 0.23987777195473095, -0.014661363646208965, -2.027954954645529, -0.035476306435143545, 2.3233678805030076, 0.08326671319745274, 0.36085284714413735]
      std: [0.3244343844169754, 0.5158281965633522, 0.2901322476548548, 0.5021871776809874, 0.5331921797732538, 0.46856794632856424, 0.7446577730524244, 0.40315882970033534]
    sequence_length_distribution:
      "15": 1.0
    frame_delta_seconds: 5.0 / 15.0
    independent_frames_probability: 0.0
    drop_action_probability: 0.0
    decoder_retry_attempts: 10

  eval_dataloader:
    batch_size: 4
    shuffle: false
    num_workers: 0
    pin_memory: false

optimizer:
  lr: 1.0e-4
  betas: [0.9, 0.95]
  weight_decay: 0.0
  eps: 1.0e-08
  grad_clip_norm: 1.0

diffusion:
  base_dimension: 4096 # from RAE paper, to determine noise schedule depending on effective latent dimension
  noise_mean: 0.0   # Set noise_mean=0.0 and noise_std=1.0 to recover a unit Gaussian prior.
  noise_std: 1.0
  noise_sampling: dimension # {"dimension", "linear", "uniform"}; choose the draw distribution
  linear_weight_slope: 0.9 # used when noise_sampling == "linear"; pdf(s) ∝ intercept + slope * s with s in [0, 1]
  linear_weight_intercept: 0.1

ema:
  enabled: false # Not sure Dreamerv4 uses it, but usually Flow matching training is better with it so...
  decay: 0.9995
  device: null

world_model: # ~400M parameters
  input_dim: 768
  latent_dim: 1024 # From RAE paper this needs to be > input_dim (or use DH head)
  action_dim: 8 # 7 for delta joint positions + 1 for gripper
  num_registers: 4
  depth: 24
  num_heads: 16
  mlp_multiplier: 4.0
  temporal_attention_interval: 4
  temporal_context_length: 9
  rope_base: 1000.0 # small because context length of WM is tiny (9)
  qk_norm_eps: 1.0e-06 # Put None for no QK norm, RAE doesn't use, Dreamerv4 does, but I think it is better to use for this kind of world model rollouts, safer.

ode_solver: # this is for evaluation
  step_size: 0.02
  min_signal: 0.0
  max_signal: 1.0
