logging:
  project: world_model
  entity: null
  run_name: ur5_soar
  output_dir: checkpoints
  log_interval: 1
  signal_level_log_limit: 100
  checkpoint_interval: 1000

trainer:
  loss_type: velocity
  loss_weighting: null
  loss_weighting_intercept: 0.1
  loss_weighting_slope: 0.9
  evaluation_interval: 500
  grad_accum_steps: 4
  precision: bf16
  seed: 10
  resume: false # true
  load_checkpoint: null

evaluator:
  video_sample_indices: all
  rollout_start_frame: 10
  rollout_horizons: [1, 5, 10, 20]
  rollout_signal_level: 0.8
  rollout_add_noise: true
  teacher_forced_batch_size: 64
  precision: bf16
  max_batches: 10

optimizer:
  lr:
    "0": 1.0e-7
    "500": 3.0e-4
  eps: 1.0e-08
  grad_clip_norm: 1.0
  weight_decay: 0.0

ema:
  enabled: false
  decay: 0.9995
  start_step: 5000

train_dataloader:
  batch_size: 256
  shuffle: true
  num_workers: 6
  pin_memory: true

train_dataset:
  sequence_length_distribution:
    "32": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    ur5_fix: 0.05
    ur5_wild: 0.2
    soar: 0.75
  reference_dataset: ur5_fix
  datasets:
    ur5_fix:
      type: lerobot
      repo_id: Gaugou/ur5_fix_5hz
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: false
      cameras:
        observation.images.front: 1.0
      action_mode: ur5_delta_absg
      independent_frames_probability: 0.3
      use_action_probability: 0.7
    ur5_wild:
      type: lerobot
      repo_id: Gaugou/ur5_wild_5hz
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: false
      cameras:
        observation.images.front: 1.0
      action_mode: ur5_delta_absg
      independent_frames_probability: 0.3
      use_action_probability: 0.7
    soar:
      type: lerobot
      repo_id: Gaugou/Soar
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: false
      cameras:
        observation.images.image: 1.0
      action_mode: soar_matchur5
      independent_frames_probability: 0.3
      use_action_probability: 0.7

eval_dataloader:
  batch_size: 8
  shuffle: false
  num_workers: 0
  pin_memory: false

eval_dataset:
  sequence_length_distribution:
    "85": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    ur5_fix_eval: 1.0
  reference_dataset: ur5_fix_eval
  datasets:
    ur5_fix_eval:
      type: lerobot
      repo_id: Gaugou/ur5_fix_5hz_eval
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: true
      cameras:
        observation.images.front: 1.0
      action_mode: ur5_delta_absg
      independent_frames_probability: 0.0
      use_action_probability: 1.0

signal_scheduler:
  mode: "resolution_shift"  # {"resolution_shift", "linear_shift", "uniform", "logit_normal"}
  min_value: 0.0
  max_value: 1.0
  logit_normal_loc: -0.8
  logit_normal_scale: 0.8

euler_solver:
  number_steps: 50
  min_denom: 0.05
  timestep_schedule: "signal"

world_model:
  input_dim: 768
  latent_dim: 1024 # 1536, 1024
  bottleneck_dim: null
  action_dim: 7
  num_registers: 4
  depth: 24 # 28, 24
  num_heads: 16 # 24, 16
  mlp_multiplier: 4 # 2.666667, 4
  temporal_attention_interval: 4
  temporal_context_length: 24
  rope_base: 10000.0
  qk_norm_eps: 1.0e-06
  attn_logit_softcapping: 50.0 # None for no softcapping -> able to use fused_attention
  use_action_token: true  # false for pretraining (no actions), true for finetuning
