logging:
  project: world_model
  entity: null
  run_name: training_ur5
  output_dir: checkpoints
  log_interval: 1
  signal_level_log_limit: 100
  checkpoint_interval: 500

trainer:
  loss_type: velocity
  loss_weighting: null
  loss_weighting_intercept: 0.1
  loss_weighting_slope: 0.9
  evaluation_interval: 10
  grad_accum_steps: 4
  precision: bf16
  seed: 3
  resume: false
  load_checkpoint: null

evaluator:
  video_sample_indices: all # null -> no videos, all -> all videos, [1, 2, 3] -> specific indices
  rollout_start_frame: 6
  rollout_signal_level: 0.8
  precision: bf16
  max_batches: 10
  denoising_metrics_indices: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 99]
  save_denoising_frames: false

optimizer:
  lr:
    "0": 1.0e-7
    "500": 3.0e-4
  eps: 1.0e-08
  grad_clip_norm: 1.0
  weight_decay: 0.0

ema:
  enabled: false
  decay: 0.9995
  start_step: 5000

train_dataloader:
  batch_size: 128
  shuffle: true
  num_workers: 6
  pin_memory: true

train_dataset:
  sequence_length_distribution:
    "30": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    ur5: 1.0
  reference_dataset: ur5
  datasets:
    ur5:
      type: lerobot
      repo_id: Gaugou/ur5_WM
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: false
      cameras:
        observation.images.front: 1.0
      action_mode: ur5_relative_local_ee_normalized
      independent_frames_probability: 0.3
      use_action_probability: 0.7

eval_dataloader:
  batch_size: 8
  shuffle: false
  num_workers: 0
  pin_memory: false

eval_dataset:
  sequence_length_distribution:
    "100": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    ur5: 1.0
  reference_dataset: ur5
  datasets:
    ur5:
      type: lerobot
      repo_id: Gaugou/ur5_WM_eval
      episodes: null
      excluded_episodes: null
      episode_startpoint_only: true
      cameras:
        observation.images.front: 1.0
      action_mode: ur5_relative_local_ee_normalized
      independent_frames_probability: 0.0
      use_action_probability: 1.0

signal_scheduler:
  mode: "logit_normal"  # {"resolution_shift", "linear_shift", "uniform", "logit_normal"}
  min_value: 0.0
  max_value: 1.0
  logit_normal_loc: -0.8
  logit_normal_scale: 0.8

euler_solver:
  number_steps: 50
  min_denom: 0.05
  timestep_schedule: "linear"

world_model:
  input_dim: 768
  latent_dim: 768
  bottleneck_dim: 64
  action_dim: 7
  num_registers: 4
  depth: 24
  num_heads: 16
  mlp_multiplier: 4
  temporal_attention_interval: 3
  temporal_context_length: 20
  rope_base: 10000.0
  qk_norm_eps: 1.0e-06
  attn_logit_softcapping: 50.0 # None for no softcapping -> able to use fused_attention
  use_action_token: true  # false for pretraining (no actions), true for finetuning