dataset:
  repo_id: lerobot/droid_1.0.1
  cameras:
    - observation.images.exterior_1_left
    - observation.images.exterior_2_left
  action_key: observation.state.cartesian_position
  episodes: [0, 1, 2, 3, 4, 5]
  sequence_length_distribution:
    2: 1.0
  frame_delta_seconds: 5.0 / 15.0

dataloader:
  batch_size: 8
  shuffle: false
  num_workers: 0
  pin_memory: true

optimizer:
  lr: 1.0e-4
  betas: [0.9, 0.95]
  weight_decay: 0.01
  eps: 1.0e-08
  grad_clip_norm: 1.0

trainer:
  max_steps: 10000
  grad_accum_steps: 1
  precision: fp32
  seed: 1234
  device: mps
  resume_checkpoint: null
  single_batch_overfit: false

logging:
  project: world_model
  entity: null
  run_name: null
  log_interval: 10
  checkpoint_interval: 1000
  output_dir: checkpoints

vision:
  encoder_repo_id: facebook/dinov2-with-registers-base
  decoder_config: rae_dino/decoder.json
  decoder_patch_size: 16
  target_size: 224

world_model:
  input_dim: 768
  latent_dim: 1024
  action_dim: 6
  num_registers: 4
  depth: 12
  num_heads: 8
  mlp_multiplier: 4.0
  temporal_attention_interval: 4
  temporal_context: 10  # Number of past frames temporal attention may attend; ensure the longest dataset clip comfortably exceeds this.
  rope_base: 10000.0
  attn_logit_soft_cap: 50.0
  qk_norm_eps: 1.0e-06
  debug:
    enabled: true
    output_dir: debug/transformer
    dummy_time_steps: 15
    num_patch_plots: 1
    num_tokens: 8  # only used for debug reports

diffusion:
  min_signal: 0.0
  max_signal: 1.0
  base_dimension: 4096
  noise_mean: 0.0   # Set noise_mean=0.0 and noise_std=1.0 to recover a unit Gaussian prior.
  noise_std: 1.0
  debug:
    enabled: true
    output_dir: debug/diffusion
    num_hist_bins: 60
    schedule_plot_points: 256
    max_time_series: 8

ema:
  enabled: true
  decay: 0.999
  device: null
