evaluator:
  config_path: configs/pretraining.yaml
  checkpoint_path: checkpoints/world_model_step_002000.pt
  use_ema_weights: true
  device: cuda

ui:
  sample_index: 0
  context_length: null
  disable_actions: false
  translation_step: 0.02
  rotation_step: 0.05
